branches:
  only:
  - master
  - xabe-build
  - development
git:
  quiet: true
  depth: false
jobs:
  include:
    - name: "Android Main Build"
      language: android
      os: linux
      dist : xenial
      addons:
        apt:
          packages:
            - autoconf
            - automake
            - libtool
            - pkg-config
            - curl
            - git
            - cmake
            - gcc
            - gperf
            - texinfo
            - yasm
            - bison
            - autogen
            - patch
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-24
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk;21.3.6528147"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
      before_install:
        - touch $HOME/.android/repositories.cfg
      before_script:
        - export ANDROID_NDK_ROOT=${ANDROID_HOME}ndk/21.3.6528147
        - rm -f ./build.log
        - wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.gz;tar zxvf nasm-2.14.02.tar.gz;cd nasm-2.14.02;./configure;make;sudo make install;cd ..
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./android.sh --no-output-redirection -d
    - name: "Android Full Build"
      language: android
      os: linux
      dist : xenial
      addons:
        apt:
          packages:
            - wget
            - git
            - build-essential
            - unzip
            - automake
            - openjdk-11-jre-headless
            - texinfo 
            - autoconf
            - libtool
            - pkg-config
            - curl
            - cmake
            - gcc
            - gperf
            - yasm
            - nasm
            - bison
            - autogen
            - patch
            - python
            - linux-headers-generic
            - libgnutls28-dev
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-24
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk;21.0.6113669"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager "build-tools;30.0.1"
        - sudo cp -f /usr/bin/aclocal /usr/bin/aclocal-1.16
        - sudo cp -f /usr/bin/aclocal /usr/bin/aclocal-1.15
        - sudo cp -f /usr/bin/automake /usr/bin/automake-1.15
        - sudo cp -f /usr/bin/automake /usr/bin/automake-1.16
      before_install:
        - touch $HOME/.android/repositories.cfg
      before_script:
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/21.0.6113669
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./android.sh --no-output-redirection -d --full --enable-gpl --enable-libvidstab --enable-rubberband --enable-x264 --enable-xvidcore
    - name: "Android LTS Build"
      language: android
      os: linux
      dist : xenial
      addons:
        apt:
          packages:
            - autoconf
            - automake
            - libtool
            - pkg-config
            - curl
            - git
            - cmake
            - gcc
            - gperf
            - texinfo
            - yasm
            - bison
            - autogen
            - patch
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-16
          - android-21
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk;21.3.6528147"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
      before_install:
        - touch $HOME/.android/repositories.cfg
      before_script:
        - export ANDROID_NDK_ROOT=${ANDROID_HOME}ndk/21.3.6528147
        - rm -f ./build.log
        - wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.gz;tar zxvf nasm-2.14.02.tar.gz;cd nasm-2.14.02;./configure;make;sudo make install;cd ..
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./android.sh --lts --no-output-redirection -d
    - name: "iOS Main Build"
      language: objective-c
      os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - nasm
          update: true
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./ios.sh --no-output-redirection --disable-arm64e
    - name: "iOS LTS Build"
      language: objective-c
      osx_image: xcode7.3
      os: osx
      addons:
        homebrew:
          packages:
            - nasm
          update: true
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./ios.sh --lts --no-output-redirection --disable-armv7 --disable-armv7s --disable-i386
    - name: "tvOS Main Build"
      language: objective-c
      os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - nasm
          update: true
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./tvos.sh --no-output-redirection
    - name: "tvOS LTS Build"
      language: objective-c
      os: osx
      osx_image: xcode7.3
      addons:
        homebrew:
          packages:
            - nasm
          update: true
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./tvos.sh --lts --no-output-redirection
