branches:
  only:
  - travis-test
sudo: false
git:
  quiet: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - curl
      - git
      - cmake
      - gcc
      - gperf
      - texinfo
      - yasm
      - nasm
      - bison
      - autogen
      - patch
  homebrew:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - curl
      - git
      - cmake
      - gcc
      - gperf
      - texinfo
      - yasm
      - nasm
      - bison
      - autogen
      - coreutils
    update: true
matrix:
  include:
    - name: "Android Main Build"
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-24
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      before_script:
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        - truncate --size 0 ./build.log
      script:
        - bash ./android.sh
        - grep -e INFO ./build.log | grep build
    - name: "Android Main Debug Build"
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-24
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      before_script:
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        - truncate --size 0 ./build.log
      script:
        - bash ./android.sh -d
        - grep -e INFO ./build.log | grep build
    - name: "Android LTS Build"
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-16
          - android-21
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      before_script:
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        - truncate --size 0 ./build.log
      script:
        - bash ./android.sh --lts
        - grep -e INFO ./build.log | grep build
    - name: "Android LTS Debug Build"
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-16
          - android-21
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      before_script:
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        - truncate --size 0 ./build.log
      script:
        - bash ./android.sh -d --lts
        - grep -e INFO ./build.log | grep build