# main section
title: mobile-ffmpeg
baseurl: "/mobile-ffmpeg"
locale: "en"
theme: jekyll-theme-modernist
markdown: kramdown

# github section
show_downloads: true
github:
  zip_url:
  tar_url: 
  owner_name: Taner Sener
  owner_url: https://github.com/tanersener